### ISSUE TITLE
Error al desplegar app

### ISSUE THREAD

**Issue by danybeth90** [emeltec/webapp-node-ejs#1]
Saludos, estoy aprendiendo a desplegar apps en mi servidor con node.js gracias al video de youtube y este repo.

El problema es que al ejecutar la app mi servidor me avisa de que se genera un error puesto que el puerto 3000 ya está en uso:

![01 captura de pantalla](https://user-images.githubusercontent.com/88804808/166393336-ace42deb-3526-483e-a1fb-893411c8a360.jpeg)

Este es el error detallado:
```ruby

returncode: 1
stdout:
> webapp-node-ejs@1.0.0 test
> node index.js
stderr:
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (/home/danielad/nodevenv/prueba1/16/lib/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/home/danielad/prueba1/index.js:48:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}

```
No tengo ninguna otra aplicación ejecutándose, por esto quiero saber si es este script el que tiene un error.

De antemano gracias.

**Comment by emeltec** [comment]
Hola, lo primero que intentaria sería cambiar el puerto (por 3001 por ejemplo) y ejecutar nuevamente.
